# Generated by Django 5.1.7 on 2025-03-07 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=100, verbose_name='队伍A')),
                ('team_b', models.CharField(max_length=100, verbose_name='队伍B')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('finished', '已结束')], default='not_started', max_length=20, verbose_name='状态')),
                ('result_winner', models.CharField(blank=True, max_length=100, null=True, verbose_name='获胜队伍')),
                ('result_score', models.CharField(blank=True, max_length=20, null=True, verbose_name='比分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛列表',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_winner', models.CharField(max_length=100, verbose_name='预测获胜队伍')),
                ('predicted_score', models.CharField(max_length=20, verbose_name='预测比分')),
                ('points_earned', models.IntegerField(default=0, verbose_name='获得积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match', verbose_name='比赛')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '竞猜',
                'verbose_name_plural': '竞猜列表',
                'unique_together': {('user', 'match')},
            },
        ),
    ]
