# Generated by Django 5.1.7 on 2025-03-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['start_time'], 'verbose_name': '比赛', 'verbose_name_plural': '比赛列表'},
        ),
        migrations.AddField(
            model_name='match',
            name='match_series',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='比赛局数'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='比赛性质'),
        ),
    ]
