# Generated by Django 5.1.7 on 2025-03-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
