# Generated by Django 5.1.7 on 2025-03-10 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_announcement_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar_is_cropped",
            field=models.BooleanField(default=False, verbose_name="头像已裁剪"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="显示在个人资料和排行榜上的名称，可以使用中文",
                max_length=50,
                verbose_name="昵称",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "该用户名已被使用"},
                help_text="用于登录的用户名，只能包含英文字母和数字",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="用户名只能包含英文字母和数字",
                        regex="^[a-zA-Z0-9]+$",
                    )
                ],
            ),
        ),
    ]
