# Generated by Django 5.1.7 on 2025-03-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_avatar_is_cropped_customuser_nickname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatar_is_cropped",
        ),
    ]
