# Generated by Django 5.1.7 on 2025-03-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_avatar_is_cropped"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_password_change",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="上次修改密码时间"
            ),
        ),
    ]
